#!/usr/bin/env bash
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generate a populated .env file for the Streamlit app using values from cdk-outputs.json.
#
# Usage: ./configure_env.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CDK_OUTPUTS="../infrastructure/cdk-outputs.json"
ENV_FILE=".env"
STACK_NAME="OrderApprovalAgent"

if [[ ! -f "$CDK_OUTPUTS" ]]; then
  echo "Error: cdk-outputs.json not found at $CDK_OUTPUTS"
  echo "Run infrastructure/deploy.sh first."
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install it with: brew install jq"
  exit 1
fi

AGENT_RUNTIME_ARN=$(jq -r ".\"$STACK_NAME\".AgentRuntimeArn" "$CDK_OUTPUTS")
SESSION_BUCKET=$(jq -r ".\"$STACK_NAME\".SessionBucketName" "$CDK_OUTPUTS")
AWS_REGION=$(jq -r ".\"$STACK_NAME\".AgentRuntimeArn" "$CDK_OUTPUTS" | cut -d: -f4)

for var in AGENT_RUNTIME_ARN SESSION_BUCKET; do
  if [[ -z "${!var}" || "${!var}" == "null" ]]; then
    echo "Error: $var not found in $CDK_OUTPUTS under stack '$STACK_NAME'."
    exit 1
  fi
done

cat > "$ENV_FILE" <<EOF
# Auto-generated by infrastructure/configure_env.sh
AWS_REGION=$AWS_REGION
AGENT_RUNTIME_ARN=$AGENT_RUNTIME_ARN
SESSION_BUCKET=$SESSION_BUCKET

# Local development (optional)
# LOCAL_AGENT_URL=http://localhost:8080/invocations
# LOCAL_MODE=true
EOF

echo "Written to $ENV_FILE"
