#!/usr/bin/env bash
# Copyright 2026 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Generate a populated .env file for local agent development using values from cdk-outputs.json.
#
# Usage: ./configure_env.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CDK_OUTPUTS="../infrastructure/cdk-outputs.json"
ENV_FILE=".env"
STACK_NAME="OrderApprovalAgent"

if [[ ! -f "$CDK_OUTPUTS" ]]; then
  echo "Error: cdk-outputs.json not found at $CDK_OUTPUTS"
  echo "Run infrastructure/deploy.sh first."
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "Error: jq is required. Install it with: brew install jq"
  exit 1
fi

SESSION_BUCKET=$(jq -r ".\"$STACK_NAME\".SessionBucketName" "$CDK_OUTPUTS")
MODEL_ID=$(jq -r ".\"$STACK_NAME\".ModelId" "$CDK_OUTPUTS")
AWS_REGION=$(jq -r ".\"$STACK_NAME\".AgentRuntimeArn" "$CDK_OUTPUTS" | cut -d: -f4)

for var in SESSION_BUCKET MODEL_ID; do
  if [[ -z "${!var}" || "${!var}" == "null" ]]; then
    echo "Error: $var not found in $CDK_OUTPUTS under stack '$STACK_NAME'."
    exit 1
  fi
done

cat > "$ENV_FILE" <<EOF
# Auto-generated by src/configure_env.sh
SESSION_BUCKET=$SESSION_BUCKET
AWS_DEFAULT_REGION=$AWS_REGION
MODEL_ID=$MODEL_ID
EOF

echo "Written to $ENV_FILE"
